# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        public_uploads_adapter:
            local:
                directory: '%kernel.project_dir%/public/%uploads_dir_name%'

        private_uploads_adapter:
            local:
                directory: '%kernel.project_dir%/storage/uploads'

        template_uploads_adapter:
            local:
                directory: '%kernel.project_dir%/templates'

        import_uploads_adapter:
            local:
                directory: '%kernel.project_dir%/import_uploaded'

    filesystems:
        public_uploads_filesystem:
            adapter: public_uploads_adapter

        private_uploads_filesystem:
            adapter: private_uploads_adapter
            mount: private_uploads_fs

        template_uploads_filesystem:
            adapter: template_uploads_adapter

        import_uploads_filesystem:
            adapter: import_uploads_adapter