vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        private_post_reference:
            uri_prefix: /storage/uploads
            upload_destination: private_uploads_fs
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
